/** Union of all message keys generated by WXT from public/_locales. */
export type I18nKey = Parameters<typeof browser.i18n.getMessage>[0];

/**
 * Get a localized message from _locales.
 * Falls back to the key itself if not found.
 */
export function t(key: I18nKey, ...substitutions: string[]): string {
	try {
		const message = browser.i18n.getMessage(key, substitutions);
		return message || key;
	} catch {
		return key;
	}
}
